[package]
name = "load-balancer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.2"
serde = "1.0.189"
serde_derive = "1.0.189"
log = "0.4.20"
env_logger = "0.10.0"
rand = "0.8.5"

[build-dependencies]