# Test Configuration for RustStrom

http_address = "0.0.0.0:8000"

# Enable metrics endpoint
prometheus_metrics_address = "0.0.0.0:9090"

[[backend_pools]]
matcher = "Path('/')"
addresses = ["127.0.0.1:8080", "127.0.0.1:8081", "127.0.0.1:8082"]
schemes = ["HTTP"]
strategy = { RoundRobin = {} }

[backend_pools.health_config]
slow_threshold = 300
timeout = 1000
path = "/"
