[frontend]
bind = "*:80"

[backend]
[[backend.entries]]
domain = "backend.uz"
balance = "roundrobin"
servers = [
    { name = "backend_server_1", ip = "192.168.1.201", ports = [8080, 15051, 15060, 15078] }
]

[[backend.entries]]
domain = "ui.uz"
balance = "roundrobin"
servers = [
    { name = "ui_server_1", ip = "192.168.1.202", ports = [8080] }
]